import { z } from 'zod';

const MAX_FILE_SIZE = 5 * 1024 * 1024; //5MB

const ACCEPTED_TYPES = [
  'application/pdf', //pdf
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // .docx
];

// Validate the data submitted by the resume upload form.
export const resumeUploadSchema = z.object({
  
  targetJob: z.string().min(2, 'Enter a target job title'),

  selectedCompanies: z.array(z.string()),

  // Validate that a resume file was actually selected.
  resumeFile: z
    .instanceof(File, { message: 'Please select a resume file' })

    // Reject files larger than 5 MB.
    .refine(
      (file) => file.size <= MAX_FILE_SIZE, 'File must be under 5MB'
    )

    // Reject file formats other than PDF or DOCX.
    .refine(
      (file) => ACCEPTED_TYPES.includes(file.type),
      'Only PDF or DOCX files are allowed'
    ),
});

// Create a TypeScript type directly from the upload schema.
export type ResumeUploadFormData = z.infer<typeof resumeUploadSchema>;


// Define the structure of a certification returned by the backend.
const certificationSchema = z.object({
  // Short certification name, such as AWS SAA.
  name: z.string(),

  // Full certification name.
  full_name: z.string(),

  // Certification provider, if available.
  provider: z.string().nullable(),

  // Certification website, if available.
  url: z.string().nullable(),
});


// Define the structure of the resume analysis returned by Flask.
const analysisResultSchema = z.object({
  // Skills detected in the user's resume.
  skills: z.array(z.string()),

  // Compare the user's skills against the target job requirements.
  skill_gap: z.object({
    matched_required_skills: z.array(z.string()),

    matched_optional_skills: z.array(z.string()),

    missing_required_skills: z.array(z.string()),

    missing_optional_skills: z.array(z.string()),
  }),

  // Compare the user's certifications against job requirements.
  certifications: z.object({
    matched_certifications: z.array(certificationSchema),

    missing_required_certifications: z.array(certificationSchema),

    missing_optional_certifications: z.array(certificationSchema),
  }),
});

export const resumeSchema = z.object({
  id: z.string().uuid(),

  user_id: z.string().uuid(),

  storage_path: z.string(),

  original_filename: z.string(),

  file_size: z.number(),

  target_job: z.string(),

  selected_companies: z.array(z.string()),

  status: z.enum(['uploaded', 'processing', 'completed', 'failed']),
  
  created_at: z.string(),

  updated_at: z.string(),

  // Analysis generated by the Flask backend.
  // This is null until the resume finishes processing.
  analysis_result: analysisResultSchema.nullable(),
});

export type Resume = z.infer<typeof resumeSchema>;