// Dashboard page displays the completed resume analysis and recommendations.
'use client';

import { useSearchParams } from 'next/navigation';

import { useQuery } from '@tanstack/react-query';

import DashboardHeader from '@/features/dashboard/components/DashboardHeader';
import CompanyMatchCarousel from '@/features/dashboard/components/CompanyMatchCarousel';
import AssessmentSidebar from '@/features/dashboard/components/AssessmentSidebar';
import KeywordSkillOptimization from '@/features/dashboard/components/KeywordSkillOptimization';
import CertificationRecommendations from '@/features/dashboard/components/CertificationRecommendations';
import FormattingReadability from '@/features/dashboard/components/FormattingReadability';
import KeyStrengths from '@/features/dashboard/components/KeyStrengths';
import SmartSuggestions from '@/features/dashboard/components/SmartSuggestions';

import { getResume } from '@/features/resume-upload/services/getResume';

import { mockData } from './data';

export default function DashboardPage() {
  // Read the resume ID passed through the dashboard URL.
  const searchParams = useSearchParams();

  // Get the resume ID used to load the user's analysis.
  const resumeId = searchParams.get('resumeId');

  // Fetch the selected resume from Supabase.
  const { data: resume, isLoading } = useQuery({
    // Cache each resume separately using its ID.
    queryKey: ['resume', resumeId],

    // Fetch the resume when React Query runs this query.
    queryFn: () => getResume(resumeId!),

    // Don't query Supabase until a resume ID exists.
    enabled: !!resumeId,
  });

  // Show a loading state while the resume is being fetched.
  if (!resumeId || isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        Loading your results...
      </div>
    );
  }

  // Get the analysis generated by the Flask backend.
  const analysis = resume?.analysis_result;

  // Convert skill-gap data into the format expected by the UI component.
  const skillEntries = analysis
    ? [
        // Mark matched required skills as present and required.
        ...analysis.skill_gap.matched_required_skills.map((skill) => ({
          skill,
          present: true,
          importance: 'required' as const,
        })),

        // Mark matched optional skills as present and optional.
        ...analysis.skill_gap.matched_optional_skills.map((skill) => ({
          skill,
          present: true,
          importance: 'optional' as const,
        })),

        // Mark missing required skills as absent and required.
        ...analysis.skill_gap.missing_required_skills.map((skill) => ({
          skill,
          present: false,
          importance: 'required' as const,
        })),

        // Mark missing optional skills as absent and optional.
        ...analysis.skill_gap.missing_optional_skills.map((skill) => ({
          skill,
          present: false,
          importance: 'optional' as const,
        })),
      ]
    : [];

  return (
    <div className="min-h-screen bg-gray-50 pt-20 pb-20 px-4">
      <DashboardHeader />

      <div className="max-w-7xl mx-auto mt-6 flex gap-6 items-start">
        {/* Sidebar containing the overall assessment information. */}
        <div className="w-72 shrink-0 flex flex-col gap-4">
          <AssessmentSidebar
            score={mockData.score}
            sections={mockData.sections}
          />
        </div>

        {/* Main dashboard content containing analysis and recommendations. */}
        <div className="flex-1 flex flex-col gap-4">
          {analysis ? (
            <>
              {/* Display skills matched against the selected target job. */}
              <KeywordSkillOptimization skills={skillEntries} />

              {/* Display matched and missing certification recommendations. */}
              <CertificationRecommendations
                matched={analysis.certifications.matched_certifications}
                missingRequired={
                  analysis.certifications.missing_required_certifications
                }
                missingOptional={
                  analysis.certifications.missing_optional_certifications
                }
              />
            </>
          ) : (
            // Show this when Flask has not produced an analysis yet.
            <p className="text-gray-400">
              Analysis not available yet.
            </p>
          )}

          {/* Company recommendations currently use mock data. */}
          <CompanyMatchCarousel companies={mockData.companyMatches} />

          {/* Resume formatting and readability results currently use mock data. */}
          <FormattingReadability
            grammarIssues={mockData.grammarIssues}
          />

          {/* Display strengths and improvement suggestions side by side. */}
          <div className="grid grid-cols-2 gap-4">
            <KeyStrengths strengths={mockData.strengths} />
            <SmartSuggestions improvements={mockData.improvements} />
          </div>
        </div>
      </div>
    </div>
  );
}